export const theme = {
  bg: '#0b0d12',
  surface: '#18181b',
  surface2: '#27272a',
  border: '#2a2d36',
  text: '#e6e8ee',
  muted: '#6b7280',
  accent: '#6366f1',
  accentDim: 'rgba(99, 102, 241, 0.15)',
  red: '#ef4444',
  green: '#22c55e',
  orange: '#f97316',
  blue: '#3b82f6',
  radius: 10,
  font: undefined as undefined,
} as const;

export const statusColor: Record<string, string> = {
  new: theme.blue,
  approved: theme.green,
  rejected: theme.red,
  skipped: theme.muted,
  needs_tailoring: theme.orange,
  tailoring: theme.orange,
  tailored: theme.orange,
  ready_to_apply: theme.accent,
  applied: theme.accent,
  interview_invite: '#a855f7',
  declined: theme.red,
  on_hold: theme.muted,
  submitting: theme.orange,
  submission_failed: theme.red,
  fetched: theme.muted,
  prescored: theme.muted,
};
